# Tip: application.properties 를 사용하셔도 무방합니다만,
# 굳이 yml 로 변경한 이유는 properties 에 비해 상대적으로 유연한 구조를 가졌기 때문입니다.
# yml 은 상위 계층에 대한 표현, List 등을 완전하게 표현할수가 있습니다.
# 최근의 많은 도구들이 yml 설정을 지원하기 때문에 이참에 시작해보시는 것을 추천드립니다.

spring:
  h2:
    console:
      enabled: true
